name: hello-world
on: 
  workflow_dispatch:

# Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Amruta'
        # Input has to be provided for the workflow to run
        required: true
jobs:
   my-job:
      runs-on: ubuntu-latest
      steps:
        - name: my-step
          run: echo "Hello World!"
   greet:
    runs-on: ubuntu_latest
    steps:
        - name: Send greeting
          run: echo "Hello ${{ github.event.inputs.name }}"
